/**
 * Тест 5: Генерация изображений через Google AI.
 *
 * Пользователь вводит промпт — тестируем генерацию через все
 * доступные модели (Gemini Image + Imagen 4).
 * Результат: сетка с картинками или ошибками от каждой модели.
 */

import React, { useEffect, useState } from 'react';
import {
    useImageGenerationTest,
    ImageGenerationResult,
    ImageModelStatus,
} from './useImageGenerationTest';

// ─── Цвета методов ──────────────────────────────────────

const METHOD_COLORS: Record<string, { bg: string; text: string; label: string }> = {
    gemini: { bg: 'bg-blue-100', text: 'text-blue-700', label: 'Gemini (generateContent)' },
    imagen: { bg: 'bg-purple-100', text: 'text-purple-700', label: 'Imagen (predict)' },
};

// ─── Компонент: Прогресс генерации ──────────────────────

const GenerationProgress: React.FC<{
    progress: ImageModelStatus[];
    models: { display_name: string; model_id: string }[];
}> = ({ progress, models }) => {
    const done = progress.filter(p => p.status === 'done').length;
    const total = progress.length;
    const current = progress.find(p => p.status === 'generating');
    const currentModel = current ? models.find(m => m.model_id === current.model_id) : null;

    if (total === 0) return null;

    return (
        <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-4">
            <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-purple-800">
                    Генерация: {done} / {total}
                </span>
                <span className="text-xs text-purple-600">
                    {Math.round((done / total) * 100)}%
                </span>
            </div>
            <div className="w-full bg-purple-200 rounded-full h-2 mb-2">
                <div
                    className="bg-purple-600 h-2 rounded-full transition-all duration-500"
                    style={{ width: `${(done / total) * 100}%` }}
                />
            </div>
            {currentModel && (
                <p className="text-xs text-purple-600 animate-pulse">
                    Генерируем через: {currentModel.display_name}...
                </p>
            )}
        </div>
    );
};

// ─── Компонент: Карточка результата ─────────────────────

const ImageResultCard: React.FC<{ result: ImageGenerationResult }> = ({ result }) => {
    const [showDetails, setShowDetails] = useState(false);
    const { result: r } = result;
    const methodColor = METHOD_COLORS[result.method] || { bg: 'bg-gray-100', text: 'text-gray-700', label: result.method };

    const isQuota = !r.success && r.http_status === 429;
    const borderColor = r.success
        ? 'border-green-300'
        : isQuota
            ? 'border-yellow-300'
            : 'border-red-300';

    return (
        <div className={`border-2 rounded-xl overflow-hidden bg-white ${borderColor}`}>
            {/* Шапка */}
            <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
                <div className="flex items-center justify-between">
                    <div className="min-w-0 flex-1">
                        <p className="font-bold text-gray-900 text-sm truncate">{result.display_name}</p>
                        <p className="text-xs text-gray-500 font-mono">{result.model_id}</p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0 ml-2">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-medium ${methodColor.bg} ${methodColor.text}`}>
                            {methodColor.label}
                        </span>
                        <span className="text-xs text-gray-400">{r.elapsed_ms}ms</span>
                        {r.http_status && (
                            <span className={`text-xs font-mono px-1.5 py-0.5 rounded ${
                                r.http_status === 200 ? 'bg-green-200 text-green-800'
                                    : r.http_status === 429 ? 'bg-yellow-200 text-yellow-800'
                                        : 'bg-red-200 text-red-800'
                            }`}>
                                {r.http_status}
                            </span>
                        )}
                    </div>
                </div>
            </div>

            {/* Тело: изображение или ошибка */}
            <div className="p-4">
                {r.success && r.image_base64 ? (
                    <div className="space-y-3">
                        {/* Сгенерированное изображение */}
                        <div className="flex justify-center">
                            <img
                                src={`data:${r.image_mime || 'image/png'};base64,${r.image_base64}`}
                                alt={`Generated by ${result.display_name}`}
                                className="max-w-full max-h-[400px] rounded-lg shadow-md border border-gray-200 object-contain"
                            />
                        </div>
                        {/* Текст ответа (если есть) */}
                        {r.response_text && (
                            <p className="text-xs text-gray-500 text-center italic">{r.response_text}</p>
                        )}
                        {/* Статус */}
                        <div className="flex items-center justify-center gap-2">
                            <span className="text-green-600 text-sm font-bold">✓ Изображение сгенерировано</span>
                            <span className="text-xs text-gray-400">({r.elapsed_ms}ms)</span>
                        </div>
                    </div>
                ) : isQuota ? (
                    <div className="text-center py-6">
                        <span className="text-3xl">⏳</span>
                        <p className="text-yellow-700 font-medium mt-2">Квота исчерпана (429)</p>
                        <p className="text-xs text-yellow-600 mt-1">Модель доступна, но лимит запросов исчерпан. Попробуйте позже.</p>
                    </div>
                ) : (
                    <div className="text-center py-6">
                        <span className="text-3xl">❌</span>
                        <p className="text-red-700 font-medium mt-2">Ошибка генерации</p>
                        {r.error && (
                            <p className="text-xs text-red-600 mt-1 max-w-md mx-auto break-words">
                                {r.error.message}
                            </p>
                        )}
                        {r.response_text && (
                            <p className="text-xs text-gray-500 mt-1">{r.response_text}</p>
                        )}
                    </div>
                )}
            </div>

            {/* Кнопка деталей */}
            {r.error && (
                <div className="border-t border-gray-100 px-4 py-2">
                    <button
                        onClick={() => setShowDetails(!showDetails)}
                        className="text-xs text-gray-400 hover:text-gray-600 transition-colors"
                    >
                        {showDetails ? '▲ Скрыть детали' : '▼ Показать детали'}
                    </button>
                    {showDetails && r.error && (
                        <div className="mt-2 bg-gray-50 rounded p-2 text-xs space-y-1">
                            {r.error.code && <p><span className="font-medium">Код:</span> {r.error.code}</p>}
                            <p className="break-words"><span className="font-medium">Сообщение:</span> {r.error.message}</p>
                            {r.error.status && <p><span className="font-medium">Статус:</span> {r.error.status}</p>}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
};

// ─── Главный компонент ──────────────────────────────────

export const ImageGenerationTest: React.FC = () => {
    const {
        apiKey, setApiKey,
        proxyUrl, setProxyUrl,
        prompt, setPrompt,
        models, modelsLoaded, loadModels,
        isLoading, progress, results, error,
        generateSingle, generateAll,
    } = useImageGenerationTest();

    const [selectedModelId, setSelectedModelId] = useState<string>('');
    const [mode, setMode] = useState<'all' | 'single'>('all');

    // Загружаем модели при монтировании
    useEffect(() => {
        if (!modelsLoaded) {
            loadModels();
        }
    }, [modelsLoaded, loadModels]);

    // Устанавливаем первую модель при загрузке
    useEffect(() => {
        if (models.length > 0 && !selectedModelId) {
            setSelectedModelId(models[0].model_id);
        }
    }, [models, selectedModelId]);

    // Сводка результатов
    const successCount = results.filter(r => r.result.success).length;
    const quotaCount = results.filter(r => !r.result.success && r.result.http_status === 429).length;
    const failCount = results.filter(r => !r.result.success && r.result.http_status !== 429).length;

    return (
        <div className="h-full overflow-y-auto">
            <div className="max-w-6xl mx-auto p-6 space-y-6">
                {/* Заголовок */}
                <div>
                    <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                        🎨 Тест 5: Генерация изображений
                    </h2>
                    <p className="text-sm text-gray-500 mt-1">
                        Введите промпт — каждая модель попробует сгенерировать изображение.
                        Gemini модели используют generateContent + IMAGE, Imagen — predict endpoint.
                    </p>
                </div>

                {/* Настройки */}
                <div className="bg-white border border-gray-200 rounded-lg p-4 space-y-4">
                    <h3 className="text-sm font-bold text-gray-700">Параметры</h3>

                    {/* API Key */}
                    <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">
                            Google AI API Key <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="password"
                            value={apiKey}
                            onChange={e => setApiKey(e.target.value)}
                            placeholder="AIzaSy..."
                            className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 font-mono"
                        />
                    </div>

                    {/* Прокси */}
                    <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">Прокси (опционально)</label>
                        <input
                            type="text"
                            value={proxyUrl}
                            onChange={e => setProxyUrl(e.target.value)}
                            placeholder="http://user:pass@host:port"
                            className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 font-mono"
                        />
                    </div>

                    {/* Промпт */}
                    <div>
                        <label className="block text-xs font-medium text-gray-600 mb-1">
                            Промпт для генерации <span className="text-red-500">*</span>
                        </label>
                        <textarea
                            value={prompt}
                            onChange={e => setPrompt(e.target.value)}
                            placeholder="A cute orange cat sitting on a windowsill, watercolor style"
                            rows={3}
                            className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 resize-none"
                        />
                    </div>

                    {/* Режим */}
                    <div>
                        <label className="block text-xs font-medium text-gray-600 mb-2">Режим</label>
                        <div className="flex gap-2">
                            <button
                                onClick={() => setMode('all')}
                                className={`px-4 py-2 text-sm rounded-md border transition-colors ${
                                    mode === 'all'
                                        ? 'bg-purple-600 text-white border-purple-600'
                                        : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-50'
                                }`}
                            >
                                Все модели ({models.length})
                            </button>
                            <button
                                onClick={() => setMode('single')}
                                className={`px-4 py-2 text-sm rounded-md border transition-colors ${
                                    mode === 'single'
                                        ? 'bg-purple-600 text-white border-purple-600'
                                        : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-50'
                                }`}
                            >
                                Одна модель
                            </button>
                        </div>
                    </div>

                    {/* Выбор модели (single mode) */}
                    {mode === 'single' && (
                        <div>
                            <label className="block text-xs font-medium text-gray-600 mb-1">Модель</label>
                            <select
                                value={selectedModelId}
                                onChange={e => setSelectedModelId(e.target.value)}
                                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                            >
                                {models.map(m => (
                                    <option key={m.model_id} value={m.model_id}>
                                        {m.display_name} ({m.method})
                                    </option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* Кнопка */}
                    <button
                        onClick={mode === 'all' ? generateAll : () => generateSingle(selectedModelId)}
                        disabled={isLoading || !apiKey.trim() || !prompt.trim()}
                        className={`w-full py-3 rounded-lg text-white font-bold text-sm transition-all ${
                            isLoading || !apiKey.trim() || !prompt.trim()
                                ? 'bg-gray-400 cursor-not-allowed'
                                : 'bg-purple-600 hover:bg-purple-700 shadow-md hover:shadow-lg'
                        }`}
                    >
                        {isLoading
                            ? '🎨 Генерация...'
                            : mode === 'all'
                                ? `🎨 Сгенерировать через все ${models.length} моделей`
                                : '🎨 Сгенерировать'
                        }
                    </button>
                </div>

                {/* Ошибка */}
                {error && (
                    <div className="bg-red-50 border border-red-300 text-red-800 rounded-lg px-4 py-3 text-sm">
                        <span className="font-bold">Ошибка:</span> {error}
                    </div>
                )}

                {/* Прогресс */}
                {isLoading && progress.length > 0 && (
                    <GenerationProgress progress={progress} models={models} />
                )}

                {/* Сводка (когда есть результаты) */}
                {results.length > 0 && !isLoading && (
                    <div className="bg-white border border-gray-200 rounded-lg p-4">
                        <h3 className="text-lg font-bold text-gray-900 mb-3">📊 Сводка</h3>
                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                            <div className="bg-gray-50 rounded-lg p-3 text-center">
                                <p className="text-2xl font-bold text-gray-900">{results.length}</p>
                                <p className="text-xs text-gray-500">Всего</p>
                            </div>
                            <div className="bg-green-50 rounded-lg p-3 text-center">
                                <p className="text-2xl font-bold text-green-700">{successCount}</p>
                                <p className="text-xs text-green-600">Сгенерировано ✓</p>
                            </div>
                            <div className="bg-yellow-50 rounded-lg p-3 text-center">
                                <p className="text-2xl font-bold text-yellow-700">{quotaCount}</p>
                                <p className="text-xs text-yellow-600">Квота ⏳</p>
                            </div>
                            <div className="bg-red-50 rounded-lg p-3 text-center">
                                <p className="text-2xl font-bold text-red-700">{failCount}</p>
                                <p className="text-xs text-red-600">Ошибка ✗</p>
                            </div>
                        </div>
                    </div>
                )}

                {/* Результаты: сетка карточек */}
                {results.length > 0 && (
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-gray-700">Результаты генерации</h3>
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                            {results.map(r => (
                                <ImageResultCard key={r.model_id} result={r} />
                            ))}
                        </div>
                    </div>
                )}

                {/* Список моделей (когда ничего не запущено) */}
                {!isLoading && results.length === 0 && !error && models.length > 0 && (
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                        <h3 className="text-sm font-bold text-gray-700 mb-3">
                            Модели для генерации изображений ({models.length})
                        </h3>
                        <div className="grid gap-2">
                            {models.map(m => {
                                const mc = METHOD_COLORS[m.method] || { bg: 'bg-gray-100', text: 'text-gray-700', label: m.method };
                                return (
                                    <div key={m.model_id} className="flex items-center gap-3 px-3 py-2 bg-white rounded-lg border border-gray-100">
                                        <span className={`px-2 py-0.5 rounded text-[10px] font-medium ${mc.bg} ${mc.text}`}>
                                            {mc.label}
                                        </span>
                                        <span className="text-sm text-gray-800 font-medium">{m.display_name}</span>
                                        <span className="text-xs text-gray-400 ml-auto">{m.description}</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};
