"""
Генератор полного набора Unicode-эмоджи для emojiData.ts.
Скачивает emoji-test.txt (Unicode 15.1), фильтрует тона кожи,
группирует по категориям с русскими названиями и ключевыми словами.
"""

import urllib.request
import re
import json
import os

# === Настройки ===
EMOJI_TEST_URL = "https://unicode.org/Public/emoji/15.1/emoji-test.txt"
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "features", "emoji", "data", "emojiData.ts")

# Коды модификаторов тона кожи (исключаем)
SKIN_TONE_MODIFIERS = {"1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"}

# === Маппинг категорий Unicode → Русские названия + иконка ===
CATEGORY_MAP = {
    "Smileys & Emotion": ("Эмоции", "😊"),
    "People & Body": ("Люди и тело", "🤚"),
    "Animals & Nature": ("Животные и природа", "🐶"),
    "Food & Drink": ("Еда и напитки", "🍔"),
    "Travel & Places": ("Путешествия и места", "✈️"),
    "Activities": ("Активности", "⚽"),
    "Objects": ("Предметы", "💡"),
    "Symbols": ("Символы", "❤️"),
    "Flags": ("Флаги", "🏳️"),
}

# === Русские переводы для популярных эмоджи (английское имя → русское) ===
# Покрывает самые частые. Остальные будут с английскими именами.
RUSSIAN_NAMES = {
    # === Эмоции ===
    "grinning face": "Ухмылка",
    "grinning face with big eyes": "Радость",
    "grinning face with smiling eyes": "Радостная улыбка",
    "beaming face with smiling eyes": "Сияющая улыбка",
    "grinning squinting face": "Смех",
    "grinning face with sweat": "Улыбка в поту",
    "rolling on the floor laughing": "Катается от смеха",
    "face with tears of joy": "Слёзы радости",
    "slightly smiling face": "Лёгкая улыбка",
    "upside-down face": "Перевёрнутое лицо",
    "melting face": "Тающее лицо",
    "winking face": "Подмигивание",
    "smiling face with smiling eyes": "Улыбка с закрытыми глазами",
    "smiling face with halo": "Ангелочек",
    "smiling face with hearts": "Влюблённое лицо",
    "smiling face with heart-eyes": "Влюблённые глаза",
    "star-struck": "Звёздные глаза",
    "face blowing a kiss": "Воздушный поцелуй",
    "kissing face": "Поцелуй",
    "smiling face": "Улыбающееся лицо",
    "kissing face with closed eyes": "Поцелуй с закрытыми глазами",
    "kissing face with smiling eyes": "Поцелуй с улыбкой",
    "smiling face with tear": "Улыбка со слезой",
    "face savoring food": "Вкусняшка",
    "face with tongue": "Язык",
    "winking face with tongue": "Подмигивание с языком",
    "zany face": "Шальное лицо",
    "squinting face with tongue": "Дразнится",
    "money-mouth face": "Денежный рот",
    "smiling face with open hands": "Обнимашки",
    "face with hand over mouth": "Рука у рта",
    "face with open eyes and hand over mouth": "Прикрывает рот",
    "face with peeking eye": "Подсматривает",
    "shushing face": "Тсс!",
    "thinking face": "Думает",
    "saluting face": "Отдаёт честь",
    "zipper-mouth face": "Рот на замке",
    "face with raised eyebrow": "Поднятая бровь",
    "neutral face": "Нейтральное лицо",
    "expressionless face": "Безразличие",
    "face without mouth": "Без рта",
    "dotted line face": "Пунктирное лицо",
    "face in clouds": "В облаках",
    "smirking face": "Ухмылка",
    "unamused face": "Недовольство",
    "face with rolling eyes": "Закатил глаза",
    "grimacing face": "Гримаса",
    "face exhaling": "Выдыхает",
    "lying face": "Врунишка",
    "shaking face": "Трясётся",
    "head shaking horizontally": "Качает головой",
    "head shaking vertically": "Кивает",
    "relieved face": "Облегчение",
    "pensive face": "Задумчивость",
    "sleepy face": "Сонное лицо",
    "drooling face": "Слюни",
    "sleeping face": "Спит",
    "face with medical mask": "Маска",
    "face with thermometer": "Термометр",
    "face with head-bandage": "Повязка",
    "nauseated face": "Тошнит",
    "face vomiting": "Рвота",
    "sneezing face": "Чихает",
    "hot face": "Жарко",
    "cold face": "Холодно",
    "woozy face": "Пьяное лицо",
    "face with crossed-out eyes": "Крестики на глазах",
    "face with spiral eyes": "Спирали в глазах",
    "exploding head": "Взрыв мозга",
    "cowboy hat face": "Ковбой",
    "partying face": "Вечеринка",
    "disguised face": "Маскировка",
    "smiling face with sunglasses": "Крутой",
    "nerd face": "Ботаник",
    "face with monocle": "С моноклем",
    "confused face": "Смущение",
    "face with diagonal mouth": "Косой рот",
    "worried face": "Волнение",
    "slightly frowning face": "Хмурый",
    "frowning face": "Нахмурился",
    "face with open mouth": "Рот открыт",
    "hushed face": "Тихо",
    "astonished face": "Изумление",
    "flushed face": "Покраснел",
    "pleading face": "Просящие глаза",
    "face holding back tears": "Сдерживает слёзы",
    "frowning face with open mouth": "Хмурый с открытым ртом",
    "anguished face": "Мучение",
    "fearful face": "Страх",
    "anxious face with sweat": "Тревога",
    "sad but relieved face": "Грусть",
    "crying face": "Плачет",
    "loudly crying face": "Рыдает",
    "face screaming in fear": "Крик ужаса",
    "confounded face": "Замешательство",
    "persevering face": "Терпение",
    "disappointed face": "Разочарование",
    "downcast face with sweat": "Пот от грусти",
    "weary face": "Усталость",
    "tired face": "Устал",
    "yawning face": "Зевота",
    "face with steam from nose": "Пар из носа",
    "enraged face": "В ярости",
    "angry face": "Злой",
    "face with symbols on mouth": "Ругается",
    "smiling face with horns": "Чёртик",
    "angry face with horns": "Злой чёрт",
    "skull": "Череп",
    "skull and crossbones": "Череп и кости",
    "pile of poo": "Какашка",
    "clown face": "Клоун",
    "ogre": "Чёрт",
    "goblin": "Гоблин",
    "ghost": "Привидение",
    "alien": "Инопланетянин",
    "alien monster": "Инопланетный монстр",
    "robot": "Робот",
    "grinning cat": "Кот ухмыляется",
    "cat with wry smile": "Кот ухмылка",
    "cat with tears of joy": "Кот со слезами радости",
    "smiling cat with heart-eyes": "Кот влюблён",
    "cat with wry smile": "Кот усмешка",
    "kissing cat": "Кот целует",
    "weary cat": "Кот устал",
    "crying cat": "Кот плачет",
    "pouting cat": "Кот дуется",
    "see-no-evil monkey": "Не вижу зла",
    "hear-no-evil monkey": "Не слышу зла",
    "speak-no-evil monkey": "Не говорю зла",
    "heart on fire": "Сердце в огне",
    "mending heart": "Заживающее сердце",
    "red heart": "Красное сердце",
    "orange heart": "Оранжевое сердце",
    "yellow heart": "Жёлтое сердце",
    "green heart": "Зелёное сердце",
    "blue heart": "Синее сердце",
    "purple heart": "Фиолетовое сердце",
    "brown heart": "Коричневое сердце",
    "black heart": "Чёрное сердце",
    "white heart": "Белое сердце",
    "pink heart": "Розовое сердце",
    "light blue heart": "Голубое сердце",
    "grey heart": "Серое сердце",
    "broken heart": "Разбитое сердце",
    "heart exclamation": "Сердце-восклицание",
    "two hearts": "Два сердца",
    "revolving hearts": "Вращающиеся сердца",
    "growing heart": "Растущее сердце",
    "beating heart": "Бьющееся сердце",
    "sparkling heart": "Сверкающее сердце",
    "heart with arrow": "Сердце со стрелой",
    "heart with ribbon": "Сердце с лентой",
    "heart decoration": "Декор-сердце",
    "love letter": "Любовное письмо",
    "kiss mark": "Поцелуй",
    "hundred points": "💯",
    "anger symbol": "Символ гнева",
    "collision": "Столкновение",
    "dizzy": "Головокружение",
    "sweat droplets": "Капли пота",
    "dashing away": "Убегает",
    "hole": "Дыра",
    "speech balloon": "Облако речи",
    "thought balloon": "Облако мысли",
    "zzz": "Сон",
    # === Жесты и тело ===
    "waving hand": "Машет рукой",
    "raised back of hand": "Тыльная сторона руки",
    "hand with fingers splayed": "Растопыренные пальцы",
    "raised hand": "Поднятая рука",
    "vulcan salute": "Вулканское приветствие",
    "rightwards hand": "Рука вправо",
    "leftwards hand": "Рука влево",
    "palm down hand": "Ладонь вниз",
    "palm up hand": "Ладонь вверх",
    "leftwards pushing hand": "Толкает влево",
    "rightwards pushing hand": "Толкает вправо",
    "OK hand": "ОК",
    "pinched fingers": "Щепотка",
    "pinching hand": "Совсем чуть-чуть",
    "victory hand": "Виктория",
    "crossed fingers": "Скрещённые пальцы",
    "hand with index finger and thumb crossed": "Сердечко пальцами",
    "love-you gesture": "Люблю тебя",
    "sign of the horns": "Рокер",
    "call me hand": "Позвони мне",
    "backhand index pointing left": "Палец влево",
    "backhand index pointing right": "Палец вправо",
    "backhand index pointing up": "Палец вверх",
    "middle finger": "Средний палец",
    "backhand index pointing down": "Палец вниз",
    "index pointing up": "Указательный палец вверх",
    "index pointing at the viewer": "Указывает на тебя",
    "thumbs up": "Палец вверх 👍",
    "thumbs down": "Палец вниз 👎",
    "raised fist": "Кулак",
    "oncoming fist": "Кулак навстречу",
    "left-facing fist": "Кулак влево",
    "right-facing fist": "Кулак вправо",
    "clapping hands": "Аплодисменты",
    "raising hands": "Руки вверх",
    "heart hands": "Сердце руками",
    "open hands": "Открытые руки",
    "palms up together": "Ладони вверх",
    "handshake": "Рукопожатие",
    "folded hands": "Молитва",
    "writing hand": "Пишущая рука",
    "nail polish": "Лак для ногтей",
    "selfie": "Селфи",
    "flexed biceps": "Бицепс",
    "mechanical arm": "Механическая рука",
    "mechanical leg": "Механическая нога",
    "leg": "Нога",
    "foot": "Ступня",
    "ear": "Ухо",
    "nose": "Нос",
    "brain": "Мозг",
    "anatomical heart": "Анатомическое сердце",
    "lungs": "Лёгкие",
    "tooth": "Зуб",
    "bone": "Кость",
    "eyes": "Глаза",
    "eye": "Глаз",
    "tongue": "Язык",
    "mouth": "Рот",
    "biting lip": "Кусает губу",
    "baby": "Малыш",
    "child": "Ребёнок",
    "boy": "Мальчик",
    "girl": "Девочка",
    "person": "Человек",
    "man": "Мужчина",
    "woman": "Женщина",
    "older person": "Пожилой человек",
    "old man": "Дедушка",
    "old woman": "Бабушка",
    # === Животные ===
    "dog face": "Собака",
    "cat face": "Кот",
    "mouse face": "Мышь",
    "hamster": "Хомяк",
    "rabbit face": "Кролик",
    "fox": "Лиса",
    "bear": "Медведь",
    "panda": "Панда",
    "polar bear": "Полярный медведь",
    "koala": "Коала",
    "tiger face": "Тигр",
    "lion": "Лев",
    "cow face": "Корова",
    "pig face": "Свинья",
    "pig nose": "Пятачок",
    "frog": "Лягушка",
    "monkey face": "Обезьяна",
    "monkey": "Обезьянка",
    "chicken": "Курица",
    "penguin": "Пингвин",
    "bird": "Птица",
    "hatching chick": "Вылупляется",
    "baby chick": "Цыплёнок",
    "front-facing baby chick": "Цыплёнок анфас",
    "eagle": "Орёл",
    "duck": "Утка",
    "swan": "Лебедь",
    "owl": "Сова",
    "dodo": "Додо",
    "feather": "Перо",
    "flamingo": "Фламинго",
    "peacock": "Павлин",
    "parrot": "Попугай",
    "bat": "Летучая мышь",
    "wing": "Крыло",
    "wolf": "Волк",
    "boar": "Кабан",
    "horse face": "Лошадь",
    "unicorn": "Единорог",
    "deer": "Олень",
    "moose": "Лось",
    "donkey": "Осёл",
    "bee": "Пчела",
    "beetle": "Жук",
    "butterfly": "Бабочка",
    "bug": "Муравей",
    "ladybug": "Божья коровка",
    "ant": "Муравей",
    "mosquito": "Комар",
    "fly": "Муха",
    "worm": "Червяк",
    "caterpillar": "Гусеница",
    "cockroach": "Таракан",
    "cricket": "Сверчок",
    "spider": "Паук",
    "spider web": "Паутина",
    "scorpion": "Скорпион",
    "snail": "Улитка",
    "turtle": "Черепаха",
    "snake": "Змея",
    "lizard": "Ящерица",
    "crocodile": "Крокодил",
    "T-Rex": "Тирекс",
    "sauropod": "Динозавр",
    "whale": "Кит",
    "spouting whale": "Кит с фонтаном",
    "dolphin": "Дельфин",
    "fish": "Рыба",
    "tropical fish": "Тропическая рыба",
    "blowfish": "Рыба-фугу",
    "shark": "Акула",
    "octopus": "Осьминог",
    "spiral shell": "Ракушка",
    "jellyfish": "Медуза",
    "coral": "Коралл",
    "dog": "Пёс",
    "poodle": "Пудель",
    "guide dog": "Собака-поводырь",
    "service dog": "Служебная собака",
    "cat": "Кошка",
    "black cat": "Чёрная кошка",
    "rabbit": "Кролик",
    "mouse": "Мышка",
    "rat": "Крыса",
    "chipmunk": "Бурундук",
    "hedgehog": "Ёжик",
    "beaver": "Бобёр",
    "pig": "Свинка",
    "ram": "Баран",
    "ewe": "Овца",
    "goat": "Коза",
    "camel": "Верблюд",
    "two-hump camel": "Двугорбый верблюд",
    "llama": "Лама",
    "giraffe": "Жираф",
    "elephant": "Слон",
    "mammoth": "Мамонт",
    "rhinoceros": "Носорог",
    "hippopotamus": "Бегемот",
    "cow": "Корова",
    "ox": "Бык",
    "water buffalo": "Буйвол",
    "bison": "Бизон",
    "tiger": "Тигр",
    "leopard": "Леопард",
    "horse": "Лошадь",
    "zebra": "Зебра",
    "kangaroo": "Кенгуру",
    "badger": "Барсук",
    "gorilla": "Горилла",
    "orangutan": "Орангутан",
    "sloth": "Ленивец",
    "otter": "Выдра",
    "skunk": "Скунс",
    "raccoon": "Енот",
    # === Растения ===
    "bouquet": "Букет",
    "cherry blossom": "Сакура",
    "white flower": "Белый цветок",
    "lotus": "Лотос",
    "rosette": "Розетка",
    "rose": "Роза",
    "wilted flower": "Увядший цветок",
    "hibiscus": "Гибискус",
    "sunflower": "Подсолнух",
    "blossom": "Цветок",
    "tulip": "Тюльпан",
    "hyacinth": "Гиацинт",
    "seedling": "Росток",
    "potted plant": "Растение в горшке",
    "evergreen tree": "Хвойное дерево",
    "deciduous tree": "Лиственное дерево",
    "palm tree": "Пальма",
    "cactus": "Кактус",
    "sheaf of rice": "Сноп риса",
    "herb": "Травинка",
    "shamrock": "Клевер",
    "four leaf clover": "Четырёхлистный клевер",
    "maple leaf": "Кленовый лист",
    "fallen leaf": "Опавший лист",
    "leaf fluttering in wind": "Лист на ветру",
    "mushroom": "Гриб",
    "chestnut": "Каштан",
    # === Еда ===
    "grapes": "Виноград",
    "melon": "Дыня",
    "watermelon": "Арбуз",
    "tangerine": "Мандарин",
    "lemon": "Лимон",
    "lime": "Лайм",
    "banana": "Банан",
    "pineapple": "Ананас",
    "mango": "Манго",
    "red apple": "Яблоко",
    "green apple": "Зелёное яблоко",
    "pear": "Груша",
    "peach": "Персик",
    "cherries": "Вишня",
    "strawberry": "Клубника",
    "blueberries": "Черника",
    "kiwi fruit": "Киви",
    "tomato": "Помидор",
    "olive": "Оливка",
    "coconut": "Кокос",
    "avocado": "Авокадо",
    "eggplant": "Баклажан",
    "potato": "Картошка",
    "carrot": "Морковь",
    "ear of corn": "Кукуруза",
    "hot pepper": "Острый перец",
    "bell pepper": "Болгарский перец",
    "cucumber": "Огурец",
    "leafy green": "Зелень",
    "broccoli": "Брокколи",
    "garlic": "Чеснок",
    "onion": "Лук",
    "peanuts": "Арахис",
    "beans": "Бобы",
    "bread": "Хлеб",
    "croissant": "Круассан",
    "baguette bread": "Багет",
    "flatbread": "Лепёшка",
    "pretzel": "Крендель",
    "bagel": "Бублик",
    "pancakes": "Блины",
    "waffle": "Вафля",
    "cheese wedge": "Сыр",
    "meat on bone": "Мясо на кости",
    "poultry leg": "Куриная ножка",
    "cut of meat": "Мясо",
    "bacon": "Бекон",
    "hamburger": "Гамбургер",
    "french fries": "Картофель фри",
    "pizza": "Пицца",
    "hot dog": "Хот-дог",
    "sandwich": "Сэндвич",
    "taco": "Тако",
    "burrito": "Буррито",
    "tamale": "Тамале",
    "stuffed flatbread": "Фаршированная лепёшка",
    "falafel": "Фалафель",
    "egg": "Яйцо",
    "cooking": "Жарка",
    "shallow pan of food": "Паэлья",
    "pot of food": "Рагу",
    "fondue": "Фондю",
    "bowl with spoon": "Каша",
    "green salad": "Салат",
    "popcorn": "Попкорн",
    "butter": "Масло",
    "salt": "Соль",
    "canned food": "Консервы",
    "bento box": "Бенто",
    "rice cracker": "Рисовый крекер",
    "rice ball": "Онигири",
    "cooked rice": "Рис",
    "curry rice": "Карри",
    "steaming bowl": "Рамен",
    "spaghetti": "Спагетти",
    "roasted sweet potato": "Батат",
    "oden": "Одэн",
    "sushi": "Суши",
    "fried shrimp": "Жареная креветка",
    "fish cake with swirl": "Нарутомаки",
    "moon cake": "Лунный пирог",
    "dango": "Данго",
    "dumpling": "Пельмень",
    "fortune cookie": "Печенье с предсказанием",
    "takeout box": "Коробка для еды",
    "crab": "Краб",
    "lobster": "Лобстер",
    "shrimp": "Креветка",
    "squid": "Кальмар",
    "oyster": "Устрица",
    "soft ice cream": "Мороженое",
    "shaved ice": "Лёд с сиропом",
    "ice cream": "Мороженое в стаканчике",
    "doughnut": "Пончик",
    "cookie": "Печенье",
    "birthday cake": "Торт",
    "shortcake": "Пирожное",
    "cupcake": "Капкейк",
    "pie": "Пирог",
    "chocolate bar": "Шоколадка",
    "candy": "Конфета",
    "lollipop": "Леденец",
    "custard": "Пудинг",
    "honey pot": "Горшочек мёда",
    "baby bottle": "Детская бутылочка",
    "glass of milk": "Стакан молока",
    "hot beverage": "Горячий напиток",
    "teapot": "Чайник",
    "teacup without handle": "Чашка чая",
    "sake": "Саке",
    "bottle with popping cork": "Шампанское",
    "wine glass": "Бокал вина",
    "cocktail glass": "Коктейль",
    "tropical drink": "Тропический коктейль",
    "beer mug": "Пиво",
    "clinking beer mugs": "Чокаются пивом",
    "clinking glasses": "Чокаются бокалами",
    "tumbler glass": "Виски",
    "pouring liquid": "Наливает",
    "cup with straw": "Стакан с трубочкой",
    "bubble tea": "Бабл-ти",
    "beverage box": "Коробка сока",
    "mate": "Мате",
    "ice": "Лёд",
    "chopsticks": "Палочки",
    "fork and knife with plate": "Тарелка с приборами",
    "fork and knife": "Вилка и нож",
    "spoon": "Ложка",
    "kitchen knife": "Кухонный нож",
    "jar": "Банка",
    # === Путешествия и места ===
    "globe showing Europe-Africa": "Глобус: Европа-Африка",
    "globe showing Americas": "Глобус: Америка",
    "globe showing Asia-Australia": "Глобус: Азия",
    "globe with meridians": "Глобус с меридианами",
    "world map": "Карта мира",
    "compass": "Компас",
    "snow-capped mountain": "Заснеженная гора",
    "mountain": "Гора",
    "volcano": "Вулкан",
    "mount fuji": "Фудзи",
    "camping": "Палатка",
    "beach with umbrella": "Пляж",
    "desert": "Пустыня",
    "desert island": "Необитаемый остров",
    "national park": "Национальный парк",
    "stadium": "Стадион",
    "classical building": "Классическое здание",
    "building construction": "Стройка",
    "brick": "Кирпич",
    "rock": "Камень",
    "wood": "Дерево",
    "hut": "Хижина",
    "houses": "Дома",
    "derelict house": "Заброшенный дом",
    "house": "Дом",
    "house with garden": "Дом с садом",
    "office building": "Офис",
    "Japanese post office": "Почта Японии",
    "post office": "Почта",
    "hospital": "Больница",
    "bank": "Банк",
    "hotel": "Отель",
    "love hotel": "Лав-отель",
    "convenience store": "Магазин",
    "school": "Школа",
    "department store": "Универмаг",
    "factory": "Завод",
    "Japanese castle": "Японский замок",
    "castle": "Замок",
    "wedding": "Свадьба",
    "Tokyo tower": "Токийская башня",
    "Statue of Liberty": "Статуя Свободы",
    "church": "Церковь",
    "mosque": "Мечеть",
    "synagogue": "Синагога",
    "hindu temple": "Индуистский храм",
    "kaaba": "Кааба",
    "tent": "Палатка",
    "foggy": "Туман",
    "night with stars": "Ночь со звёздами",
    "cityscape": "Город",
    "sunrise over mountains": "Восход над горами",
    "sunrise": "Восход",
    "cityscape at dusk": "Город на закате",
    "sunset": "Закат",
    "bridge at night": "Мост ночью",
    "carousel horse": "Карусель",
    "playground slide": "Горка",
    "ferris wheel": "Колесо обозрения",
    "roller coaster": "Американские горки",
    "locomotive": "Паровоз",
    "railway car": "Вагон",
    "high-speed train": "Скоростной поезд",
    "bullet train": "Синкансен",
    "train": "Поезд",
    "metro": "Метро",
    "tram": "Трамвай",
    "bus": "Автобус",
    "oncoming bus": "Автобус (спереди)",
    "trolleybus": "Троллейбус",
    "minibus": "Минибус",
    "ambulance": "Скорая помощь",
    "fire engine": "Пожарная машина",
    "police car": "Полицейская машина",
    "oncoming police car": "Полиция (спереди)",
    "taxi": "Такси",
    "oncoming taxi": "Такси (спереди)",
    "automobile": "Автомобиль",
    "oncoming automobile": "Автомобиль (спереди)",
    "sport utility vehicle": "Внедорожник",
    "pickup truck": "Пикап",
    "delivery truck": "Грузовик",
    "articulated lorry": "Фура",
    "tractor": "Трактор",
    "racing car": "Гоночная машина",
    "motorcycle": "Мотоцикл",
    "motor scooter": "Мотороллер",
    "auto rickshaw": "Моторикша",
    "bicycle": "Велосипед",
    "kick scooter": "Самокат",
    "skateboard": "Скейтборд",
    "roller skate": "Ролики",
    "fuel pump": "Заправка",
    "wheel": "Колесо",
    "police car light": "Мигалка",
    "horizontal traffic light": "Светофор",
    "vertical traffic light": "Вертикальный светофор",
    "stop sign": "Стоп",
    "construction": "Дорожные работы",
    "anchor": "Якорь",
    "ring buoy": "Спасательный круг",
    "sailboat": "Парусник",
    "canoe": "Каноэ",
    "speedboat": "Катер",
    "passenger ship": "Пассажирское судно",
    "ferry": "Паром",
    "motor boat": "Моторная лодка",
    "ship": "Корабль",
    "airplane": "Самолёт",
    "small airplane": "Маленький самолёт",
    "airplane departure": "Вылет",
    "airplane arrival": "Прилёт",
    "parachute": "Парашют",
    "seat": "Сиденье",
    "helicopter": "Вертолёт",
    "suspension railway": "Монорельс",
    "rocket": "Ракета",
    "flying saucer": "Летающая тарелка",
    "satellite": "Спутник",
    # === Погода ===
    "sun": "Солнце",
    "full moon face": "Полная луна (лицо)",
    "sun with face": "Солнце с лицом",
    "ringed planet": "Сатурн",
    "star": "Звезда",
    "glowing star": "Сияющая звезда",
    "shooting star": "Падающая звезда",
    "milky way": "Млечный путь",
    "cloud": "Облако",
    "sun behind cloud": "Солнце за облаком",
    "cloud with lightning and rain": "Гроза",
    "sun behind small cloud": "Солнце за облачком",
    "sun behind large cloud": "Солнце за тучей",
    "sun behind rain cloud": "Солнце и дождь",
    "cloud with rain": "Дождь",
    "cloud with snow": "Снег",
    "cloud with lightning": "Молния",
    "tornado": "Торнадо",
    "fog": "Туман",
    "wind face": "Ветер",
    "cyclone": "Циклон",
    "rainbow": "Радуга",
    "closed umbrella": "Закрытый зонт",
    "umbrella": "Зонт",
    "umbrella with rain drops": "Зонт с каплями",
    "snowflake": "Снежинка",
    "snowman": "Снеговик",
    "snowman without snow": "Снеговик без снега",
    "comet": "Комета",
    "fire": "Огонь",
    "droplet": "Капля",
    "water wave": "Волна",
    # === Время ===
    "hourglass done": "Песочные часы",
    "hourglass not done": "Песочные часы (текут)",
    "watch": "Часы наручные",
    "alarm clock": "Будильник",
    "stopwatch": "Секундомер",
    "timer clock": "Таймер",
    "mantelpiece clock": "Настольные часы",
    # === Активности ===
    "jack-o-lantern": "Тыква",
    "Christmas tree": "Ёлка",
    "fireworks": "Фейерверк",
    "sparkler": "Бенгальский огонь",
    "firecracker": "Петарда",
    "sparkles": "Блёстки",
    "balloon": "Шарик",
    "party popper": "Хлопушка",
    "confetti ball": "Конфетти",
    "tanabata tree": "Дерево желаний",
    "pine decoration": "Кадомацу",
    "Japanese dolls": "Японские куклы",
    "carp streamer": "Коинобори",
    "wind chime": "Ветряной колокольчик",
    "ribbon": "Лента",
    "wrapped gift": "Подарок",
    "reminder ribbon": "Памятная лента",
    "admission tickets": "Билеты",
    "ticket": "Билет",
    "military medal": "Военная медаль",
    "trophy": "Трофей",
    "sports medal": "Спортивная медаль",
    "1st place medal": "Золото",
    "2nd place medal": "Серебро",
    "3rd place medal": "Бронза",
    "soccer ball": "Футбольный мяч",
    "baseball": "Бейсбол",
    "softball": "Софтбол",
    "basketball": "Баскетбол",
    "volleyball": "Волейбол",
    "american football": "Американский футбол",
    "rugby football": "Регби",
    "tennis": "Теннис",
    "flying disc": "Фрисби",
    "bowling": "Боулинг",
    "cricket game": "Крикет",
    "field hockey": "Хоккей на траве",
    "ice hockey": "Хоккей",
    "lacrosse": "Лакросс",
    "ping pong": "Пинг-понг",
    "badminton": "Бадминтон",
    "boxing glove": "Боксёрская перчатка",
    "martial arts uniform": "Кимоно",
    "goal net": "Ворота",
    "flag in hole": "Гольф",
    "ice skate": "Коньки",
    "fishing pole": "Удочка",
    "diving mask": "Маска для дайвинга",
    "running shirt": "Спортивная майка",
    "skis": "Лыжи",
    "sled": "Санки",
    "curling stone": "Кёрлинг",
    "bullseye": "Мишень",
    "yo-yo": "Йо-йо",
    "kite": "Воздушный змей",
    "water pistol": "Водяной пистолет",
    "pool 8 ball": "Бильярд",
    "crystal ball": "Хрустальный шар",
    "magic wand": "Волшебная палочка",
    "video game": "Видеоигра",
    "joystick": "Джойстик",
    "slot machine": "Игровой автомат",
    "game die": "Игральная кость",
    "puzzle piece": "Пазл",
    "teddy bear": "Плюшевый мишка",
    "piñata": "Пиньята",
    "mirror ball": "Зеркальный шар",
    "nesting dolls": "Матрёшка",
    "spade suit": "Пики",
    "heart suit": "Черви",
    "diamond suit": "Бубны",
    "club suit": "Трефы",
    "chess pawn": "Шахматная пешка",
    "joker": "Джокер",
    "mahjong red dragon": "Маджонг",
    "flower playing cards": "Ханафуда",
    "performing arts": "Театр",
    "framed picture": "Картина",
    "artist palette": "Палитра",
    "thread": "Нитки",
    "sewing needle": "Иголка",
    "yarn": "Пряжа",
    "knot": "Узел",
    # === Предметы ===
    "glasses": "Очки",
    "sunglasses": "Солнечные очки",
    "goggles": "Защитные очки",
    "lab coat": "Лабораторный халат",
    "safety vest": "Светоотражающий жилет",
    "necktie": "Галстук",
    "t-shirt": "Футболка",
    "jeans": "Джинсы",
    "scarf": "Шарф",
    "gloves": "Перчатки",
    "coat": "Пальто",
    "socks": "Носки",
    "dress": "Платье",
    "kimono": "Кимоно",
    "sari": "Сари",
    "one-piece swimsuit": "Купальник",
    "briefs": "Трусы",
    "shorts": "Шорты",
    "bikini": "Бикини",
    "woman's clothes": "Женская одежда",
    "folding hand fan": "Веер",
    "purse": "Кошелёк",
    "handbag": "Сумочка",
    "clutch bag": "Клатч",
    "shopping bags": "Пакеты",
    "backpack": "Рюкзак",
    "thong sandal": "Шлёпанец",
    "shoe": "Мужская туфля",
    "running shoe": "Кроссовок",
    "hiking boot": "Ботинок",
    "flat shoe": "Балетка",
    "high-heeled shoe": "Каблук",
    "sandal": "Сандалия",
    "ballet shoes": "Пуанты",
    "boot": "Сапог",
    "hair pick": "Расчёска-гребень",
    "crown": "Корона",
    "woman's hat": "Шляпа",
    "top hat": "Цилиндр",
    "graduation cap": "Академическая шапочка",
    "billed cap": "Кепка",
    "military helmet": "Каска",
    "rescue worker's helmet": "Каска спасателя",
    "prayer beads": "Чётки",
    "lipstick": "Помада",
    "ring": "Кольцо",
    "gem stone": "Бриллиант",
    "muted speaker": "Без звука",
    "speaker low volume": "Тихо",
    "speaker medium volume": "Средний звук",
    "speaker high volume": "Громко",
    "loudspeaker": "Громкоговоритель",
    "megaphone": "Мегафон",
    "postal horn": "Почтовый рожок",
    "bell": "Колокольчик",
    "bell with slash": "Без звука",
    "musical score": "Ноты",
    "musical note": "Нота",
    "musical notes": "Ноты",
    "studio microphone": "Студийный микрофон",
    "level slider": "Ползунок",
    "control knobs": "Регуляторы",
    "microphone": "Микрофон",
    "headphone": "Наушники",
    "radio": "Радио",
    "saxophone": "Саксофон",
    "accordion": "Аккордеон",
    "guitar": "Гитара",
    "musical keyboard": "Клавиши",
    "trumpet": "Труба",
    "violin": "Скрипка",
    "banjo": "Банджо",
    "drum": "Барабан",
    "maracas": "Маракасы",
    "flute": "Флейта",
    "mobile phone": "Мобильный",
    "mobile phone with arrow": "Входящий вызов",
    "telephone": "Телефон",
    "telephone receiver": "Трубка",
    "pager": "Пейджер",
    "fax machine": "Факс",
    "battery": "Батарейка",
    "low battery": "Низкий заряд",
    "electric plug": "Вилка",
    "laptop": "Ноутбук",
    "desktop computer": "Компьютер",
    "printer": "Принтер",
    "keyboard": "Клавиатура",
    "computer mouse": "Мышка",
    "trackball": "Трекбол",
    "computer disk": "Гибкий диск",
    "floppy disk": "Дискета",
    "optical disk": "CD",
    "dvd": "DVD",
    "abacus": "Счёты",
    "movie camera": "Кинокамера",
    "film frames": "Кадры плёнки",
    "film projector": "Проектор",
    "clapper board": "Хлопушка кино",
    "television": "Телевизор",
    "camera": "Фотоаппарат",
    "camera with flash": "Фотоаппарат со вспышкой",
    "video camera": "Видеокамера",
    "videocassette": "Видеокассета",
    "magnifying glass tilted left": "Лупа влево",
    "magnifying glass tilted right": "Лупа вправо",
    "candle": "Свеча",
    "light bulb": "Лампочка",
    "flashlight": "Фонарик",
    "red paper lantern": "Фонарь",
    "diya lamp": "Лампа",
    "notebook with decorative cover": "Блокнот",
    "closed book": "Закрытая книга",
    "open book": "Открытая книга",
    "green book": "Зелёная книга",
    "blue book": "Синяя книга",
    "orange book": "Оранжевая книга",
    "books": "Книги",
    "notebook": "Тетрадь",
    "ledger": "Гроссбух",
    "page with curl": "Страница",
    "scroll": "Свиток",
    "page facing up": "Документ",
    "newspaper": "Газета",
    "rolled-up newspaper": "Свёрнутая газета",
    "bookmark tabs": "Закладки",
    "bookmark": "Закладка",
    "label": "Ярлык",
    "money bag": "Мешок денег",
    "coin": "Монета",
    "yen banknote": "Йена",
    "dollar banknote": "Доллар",
    "euro banknote": "Евро",
    "pound banknote": "Фунт",
    "money with wings": "Деньги с крыльями",
    "credit card": "Банковская карта",
    "receipt": "Чек",
    "chart increasing with yen": "Рост иены",
    "envelope": "Конверт",
    "e-mail": "E-mail",
    "incoming envelope": "Входящий конверт",
    "envelope with arrow": "Конверт со стрелкой",
    "outbox tray": "Исходящие",
    "inbox tray": "Входящие",
    "package": "Посылка",
    "closed mailbox with raised flag": "Почтовый ящик (полный)",
    "closed mailbox with lowered flag": "Почтовый ящик (пустой)",
    "open mailbox with raised flag": "Почтовый ящик (открыт, полный)",
    "open mailbox with lowered flag": "Почтовый ящик (открыт, пустой)",
    "postbox": "Почтовый ящик",
    "ballot box with ballot": "Урна для голосования",
    "pencil": "Карандаш",
    "black nib": "Перо",
    "fountain pen": "Авторучка",
    "pen": "Ручка",
    "paintbrush": "Кисть",
    "crayon": "Мелок",
    "memo": "Заметка",
    "briefcase": "Портфель",
    "file folder": "Папка",
    "open file folder": "Открытая папка",
    "card index dividers": "Разделители",
    "calendar": "Календарь",
    "tear-off calendar": "Отрывной календарь",
    "spiral notepad": "Блокнот на спирали",
    "spiral calendar": "Календарь на спирали",
    "card index": "Картотека",
    "chart increasing": "График вверх",
    "chart decreasing": "График вниз",
    "bar chart": "Диаграмма",
    "clipboard": "Планшет",
    "pushpin": "Кнопка",
    "round pushpin": "Круглая кнопка",
    "paperclip": "Скрепка",
    "linked paperclips": "Скрепки",
    "straight ruler": "Линейка",
    "triangular ruler": "Угольник",
    "scissors": "Ножницы",
    "card file box": "Картотека",
    "file cabinet": "Шкаф для документов",
    "wastebasket": "Корзина",
    "locked": "Замок закрыт",
    "unlocked": "Замок открыт",
    "locked with pen": "Замок с ручкой",
    "locked with key": "Замок с ключом",
    "key": "Ключ",
    "old key": "Старый ключ",
    "hammer": "Молоток",
    "axe": "Топор",
    "pick": "Кирка",
    "hammer and pick": "Молоток и кирка",
    "hammer and wrench": "Молоток и гаечный ключ",
    "dagger": "Кинжал",
    "crossed swords": "Скрещённые мечи",
    "water pistol": "Водяной пистолет",
    "boomerang": "Бумеранг",
    "bow and arrow": "Лук и стрела",
    "shield": "Щит",
    "carpentry saw": "Пила",
    "wrench": "Гаечный ключ",
    "screwdriver": "Отвёртка",
    "nut and bolt": "Гайка и болт",
    "gear": "Шестерёнка",
    "clamp": "Тиски",
    "balance scale": "Весы",
    "white cane": "Белая трость",
    "link": "Ссылка",
    "chains": "Цепи",
    "hook": "Крючок",
    "toolbox": "Ящик с инструментами",
    "magnet": "Магнит",
    "ladder": "Лестница",
    "alembic": "Перегонный куб",
    "test tube": "Пробирка",
    "petri dish": "Чашка Петри",
    "dna": "ДНК",
    "microscope": "Микроскоп",
    "telescope": "Телескоп",
    "satellite antenna": "Спутниковая антенна",
    "syringe": "Шприц",
    "drop of blood": "Капля крови",
    "pill": "Таблетка",
    "adhesive bandage": "Пластырь",
    "crutch": "Костыль",
    "stethoscope": "Стетоскоп",
    "x-ray": "Рентген",
    "door": "Дверь",
    "elevator": "Лифт",
    "mirror": "Зеркало",
    "window": "Окно",
    "bed": "Кровать",
    "couch and lamp": "Диван и лампа",
    "chair": "Стул",
    "toilet": "Унитаз",
    "plunger": "Вантуз",
    "shower": "Душ",
    "bathtub": "Ванна",
    "mouse trap": "Мышеловка",
    "razor": "Бритва",
    "lotion bottle": "Лосьон",
    "safety pin": "Булавка",
    "broom": "Метла",
    "basket": "Корзина",
    "roll of paper": "Рулон бумаги",
    "bucket": "Ведро",
    "soap": "Мыло",
    "bubbles": "Пузыри",
    "toothbrush": "Зубная щётка",
    "sponge": "Губка",
    "fire extinguisher": "Огнетушитель",
    "shopping cart": "Тележка",
    "cigarette": "Сигарета",
    "coffin": "Гроб",
    "headstone": "Надгробие",
    "funeral urn": "Урна",
    "moai": "Моаи",
    "identification card": "Удостоверение",
    # === Символы ===
    "check mark button": "Галочка",
    "check box with check": "Чекбокс",
    "cross mark": "Крестик",
    "cross mark button": "Крестик в квадрате",
    "plus": "Плюс",
    "minus": "Минус",
    "division": "Деление",
    "multiply": "Умножение",
    "infinity": "Бесконечность",
    "double exclamation mark": "Двойной восклицательный",
    "exclamation question mark": "Восклицательный и вопросительный",
    "red question mark": "Красный вопрос",
    "white question mark": "Белый вопрос",
    "white exclamation mark": "Белый восклицательный",
    "red exclamation mark": "Красный восклицательный",
    "warning": "Предупреждение",
    "radioactive": "Радиация",
    "biohazard": "Биологическая опасность",
    "up arrow": "Стрелка вверх",
    "right arrow": "Стрелка вправо",
    "down arrow": "Стрелка вниз",
    "left arrow": "Стрелка влево",
    "left-right arrow": "Стрелка влево-вправо",
    "up-down arrow": "Стрелка вверх-вниз",
    "recycling symbol": "Переработка",
    "trident emblem": "Трезубец",
    "name badge": "Именной бейдж",
    "Japanese symbol for beginner": "Японский символ новичка",
    "hollow red circle": "Красный круг",
    "check mark": "Галочка",
    "prohibited": "Запрещено",
    "no entry": "Вход запрещён",
    "peace symbol": "Символ мира",
    "yin yang": "Инь-Ян",
    "star of David": "Звезда Давида",
    "wheel of dharma": "Колесо Дхармы",
    "om": "Ом",
    "star and crescent": "Звезда и полумесяц",
    "orthodox cross": "Православный крест",
    "latin cross": "Латинский крест",
    "menorah": "Менора",
    "atom symbol": "Атом",
    "musical note": "Нота",
    "musical notes": "Ноты",
    "OK button": "ОК",
    "SOS button": "SOS",
    "FREE button": "FREE",
    "NEW button": "NEW",
    "UP! button": "UP!",
    "COOL button": "COOL",
    "VS button": "VS",
    "information": "Информация",
    "ATM sign": "Банкомат",
    "wheelchair symbol": "Инвалидная коляска",
    "men's room": "Мужской туалет",
    "women's room": "Женский туалет",
    "restroom": "Туалет",
    "baby symbol": "Пеленальная",
    "water closet": "WC",
    "passport control": "Паспортный контроль",
    "customs": "Таможня",
    "baggage claim": "Выдача багажа",
    "left luggage": "Камера хранения",
    "no smoking": "Не курить",
    "no mobile phones": "Без мобильных",
    "no littering": "Не мусорить",
    "no bicycles": "Без велосипедов",
    "no pedestrians": "Пешеходам нельзя",
    "children crossing": "Дети",
    "potable water": "Питьевая вода",
    "cinema": "Кинотеатр",
    "red circle": "Красный круг",
    "orange circle": "Оранжевый круг",
    "yellow circle": "Жёлтый круг",
    "green circle": "Зелёный круг",
    "blue circle": "Синий круг",
    "purple circle": "Фиолетовый круг",
    "brown circle": "Коричневый круг",
    "black circle": "Чёрный круг",
    "white circle": "Белый круг",
    "red square": "Красный квадрат",
    "orange square": "Оранжевый квадрат",
    "yellow square": "Жёлтый квадрат",
    "green square": "Зелёный квадрат",
    "blue square": "Синий квадрат",
    "purple square": "Фиолетовый квадрат",
    "brown square": "Коричневый квадрат",
    "black large square": "Чёрный квадрат",
    "white large square": "Белый квадрат",
    "red triangle pointed up": "Красный треугольник вверх",
    "red triangle pointed down": "Красный треугольник вниз",
    "diamond with a dot": "Ромб с точкой",
    "large orange diamond": "Большой оранжевый ромб",
    "large blue diamond": "Большой синий ромб",
    "small orange diamond": "Маленький оранжевый ромб",
    "small blue diamond": "Маленький синий ромб",
    "white medium square": "Белый средний квадрат",
    "black medium square": "Чёрный средний квадрат",
    "white medium-small square": "Белый квадратик",
    "black medium-small square": "Чёрный квадратик",
    "black small square": "Маленький чёрный квадрат",
    "white small square": "Маленький белый квадрат",
}

def download_emoji_test():
    """Скачивает emoji-test.txt из Unicode."""
    print("Скачиваю emoji-test.txt...")
    req = urllib.request.Request(EMOJI_TEST_URL, headers={"User-Agent": "Mozilla/5.0"})
    resp = urllib.request.urlopen(req)
    data = resp.read().decode("utf-8")
    print(f"Скачано: {len(data)} символов")
    return data


def parse_emoji_test(data: str):
    """
    Парсит emoji-test.txt.
    Возвращает список: [{ group, subgroup, codes, char, name, version }]
    """
    emojis = []
    current_group = ""
    current_subgroup = ""

    for line in data.split("\n"):
        line = line.strip()
        if line.startswith("# group:"):
            current_group = line.split("# group:")[1].strip()
            continue
        if line.startswith("# subgroup:"):
            current_subgroup = line.split("# subgroup:")[1].strip()
            continue
        if not line or line.startswith("#"):
            continue

        # Парсим строку: 1F600 ; fully-qualified # 😀 E1.0 grinning face
        if "; fully-qualified" not in line:
            continue

        parts = line.split(";")
        codes_str = parts[0].strip()
        codes = codes_str.split()

        # Пропускаем модификаторы тона кожи
        has_skin_tone = any(c in SKIN_TONE_MODIFIERS for c in codes)
        if has_skin_tone:
            continue

        # Пропускаем группу Component (модификаторы)
        if current_group == "Component":
            continue

        # Извлекаем символ и имя из комментария
        comment = parts[1].split("#")[1].strip() if "#" in parts[1] else ""
        # Формат: 😀 E1.0 grinning face
        comment_parts = comment.split(" ", 2)
        if len(comment_parts) < 3:
            continue

        char = comment_parts[0]
        version = comment_parts[1]  # E1.0 и т.д.
        name = comment_parts[2] if len(comment_parts) > 2 else ""

        emojis.append({
            "group": current_group,
            "subgroup": current_subgroup,
            "codes": codes,
            "char": char,
            "name": name,
            "version": version,
        })

    return emojis


def get_russian_name(english_name: str) -> str:
    """Возвращает русское название эмоджи или английское как фоллбэк."""
    return RUSSIAN_NAMES.get(english_name, english_name)


def generate_keywords(english_name: str, russian_name: str) -> list:
    """Генерирует ключевые слова для поиска."""
    keywords = []
    # Русские ключевые слова (разбиваем по словам)
    for word in russian_name.lower().split():
        if len(word) > 1 and word not in ("с", "в", "и", "на", "за", "от", "по", "к", "у", "о"):
            keywords.append(word)
    # Английские ключевые слова (для поиска на английском)
    for word in english_name.lower().split():
        if len(word) > 1 and word not in ("a", "an", "the", "of", "in", "on", "at", "to", "for", "with", "and"):
            keywords.append(word)
    return list(dict.fromkeys(keywords))  # Убираем дубликаты, сохраняя порядок


def escape_ts_string(s: str) -> str:
    """Экранирует строку для TypeScript."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def generate_ts(emojis: list) -> str:
    """Генерирует содержимое emojiData.ts."""
    # Группируем по category
    groups = {}
    for e in emojis:
        group = e["group"]
        if group not in groups:
            groups[group] = []
        groups[group].append(e)

    # Сортировка категорий по порядку из CATEGORY_MAP
    category_order = list(CATEGORY_MAP.keys())

    lines = []
    lines.append("export type EmojiData = {")
    lines.append("  char: string;")
    lines.append("  name: string;")
    lines.append("  keywords: string[];")
    lines.append("};")
    lines.append("")
    lines.append("export type EmojiCategory = {")
    lines.append("  name: string;")
    lines.append("  icon: string;")
    lines.append("  emojis: EmojiData[];")
    lines.append("};")
    lines.append("")
    lines.append("// Полный набор Unicode 15.1 эмоджи (без модификаторов тона кожи).")
    lines.append("// Сгенерировано автоматически скриптом generate_emoji_data.py")
    lines.append("export const emojiCategories: EmojiCategory[] = [")

    for group_key in category_order:
        if group_key not in groups:
            continue
        group_emojis = groups[group_key]
        ru_name, icon = CATEGORY_MAP.get(group_key, (group_key, "❓"))

        lines.append("  {")
        lines.append(f"    name: '{escape_ts_string(ru_name)}',")
        lines.append(f"    icon: '{icon}',")
        lines.append("    emojis: [")

        for e in group_emojis:
            ru = get_russian_name(e["name"])
            kw = generate_keywords(e["name"], ru)
            kw_str = ", ".join(f"'{escape_ts_string(k)}'" for k in kw)
            lines.append(f"      {{ char: '{e['char']}', name: '{escape_ts_string(ru)}', keywords: [{kw_str}] }},")

        lines.append("    ],")
        lines.append("  },")

    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def main():
    data = download_emoji_test()
    emojis = parse_emoji_test(data)
    print(f"Всего эмоджи (без тонов кожи и Component): {len(emojis)}")

    # Статистика по группам
    from collections import Counter
    group_counts = Counter(e["group"] for e in emojis)
    for g, c in group_counts.most_common():
        ru_name = CATEGORY_MAP.get(g, (g,))[0]
        print(f"  {ru_name}: {c}")

    ts_content = generate_ts(emojis)
    
    # Записываем файл
    output = os.path.abspath(OUTPUT_PATH)
    with open(output, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"\nФайл записан: {output}")
    print(f"Размер: {len(ts_content)} байт")


if __name__ == "__main__":
    main()
